FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o etl ./cmd/etl

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/etl /app/etl
RUN mkdir -p /app/data
ENV DATA_DIR=/app/data
CMD ["/app/etl"]